site_name: Nilan's Class 3
site_url: https://archat.github.io/class3/
theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview    
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.
    - navigation.section
    - navigation.expand
    - toc.integrate

nav:
  - Home: index.md
  - Midterm:
    - Syllabus: midterm/syllabus.md
    - LAR: midterm/lar.md
    - Kannada: midterm/kannada.md
    - Hindi: midterm/hindi.md
    - Computer Science: midterm/cs.md
    - General Science: midterm/gs.md
    - Social Science: midterm/ss.md
    - Mathematics: midterm/math.md
  - UA 02:
    - Syllabus: ua02/syllabus.md


markdown_extensions:
  - attr_list
plugins:
  - mkdocs-pdf    
  - search